server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: update
    show-sql: true


